fix: the null pointer exception of getPropertyList
Although the `category` is not required, the generated `AggregatedAppFunctionInvoker.unsafeInvoke` will convert the parameter as String.
This causes the NullPointerException when the caller invokes the
function without `category`:
```
java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
```
Fix this issue by changing `category` as an nullable argument.

Test: Manual